### ISSUE TITLE
Can not find new transaction path to listing_id: X, payment_gateway: , payment_process: preauthorize, booking: false

### ISSUE THREAD

**Issue by shamanovsky** [sharetribe/sharetribe#1112]
how to test locally?

**Comment by pilgrim2go** [comment]
I have the same issue when checking out sharetribe and run locally ( Vagrant)

**Comment by bingxie** [comment]
This issue is because the latest code, when you create new marketplace community, it will create a :preauthorize type community. So you need payment gateway setup. 

The temporary solution is to change marketplace service API:
/app/services/marketplace_service/api/marketplaces.rb:63

change :preauthorize to :none

I would like to suggest sharetribe team to support setting this using a parameter.

**Comment by rap1ds** [comment]
@bingxie @pilgrim2go That's right, this needs to be improved. The Marketplace API should take the transaction process (:preauthorize vs :none) as a parameter. 

Then CommunitiesController should create a new marketplace with :none process and IntApi::MarketplaceController should create a new marketplace with :preauthorize.

If you have time to write a PR I can quickly review and merge it.

Thanks @bingxie for spotting the issue.

**Comment by bingxie** [comment]
Thanks @rap1ds for your suggestions. So I will have a try to fix this today.

**Comment by bingxie** [comment]
@rap1ds so this issue can be closed. Thanks.
