### ISSUE TITLE
Sending emails - production

### ISSUE THREAD

**Issue by eltonokada** [sharetribe/sharetribe#1262]
Hi,

I've configured Sharetribe in a Digital Ocean VPS, everything is running fine, but the emails don't.

I created a Postmark account, changed the 
config.default.yml 
mail_delivery_method: "postmark"

But, i am still getting an error message:

Errno::ECONNREFUSED (Connection refused - connect(2) for "localhost" port 25):
  app/controllers/sessions_controller.rb:102:in `request_new_password'
  config/initializers/oneline_detailed_logging.rb:31:in `block (2 levels) in <top (required)>'
  config/initializers/oneline_detailed_logging.rb:30:in `block in <top (required)>'
  lib/rack_middleware/custom_domain_cookie.rb:20:in `call'

Any thoughts?

Thanks!

**Comment by thomassnielsen** [comment]
@eltonokada How did you fix this?

**Comment by eltonokada** [comment]
It was a problem in Digital Ocean about closed ports

**Comment by softcomet** [comment]
@eltonokada hi, can you let me know exactly regarding Digital Ocean issue? I am getting same issue now. I am trying to run the sharetribe server with production env and set the smtp config with gmail. But now I am getting the error like following.
2021-06-28T01:32:05+0000: [Worker(host:sharetribe-ubuntu pid:3368)] Job EmailConfirmationJob (id=7) (queue=default) FAILED (2 prior attempts) with Errno::ECONNREFUSED: Connection refused - connect(2) for "localhost" port 25
[Worker(host:sharetribe-ubuntu pid:3368)] Job EmailConfirmationJob (id=7) (queue=default) REMOVED permanently because of 3 consecutive failures

Any suggestion for me?
