### ISSUE TITLE
Want to do an OR search rather than AND - is this possible?

### ISSUE THREAD

**Issue by chase221** [sharetribe/sharetribe#1293]
I had a question around the implementation of the search functionality, and how to have the custom checkbox filter return all listings that match any checked checkbox.

Here’s where I am at so far:
 
I have a custom listing field/filter called “delivery zone” that is a checkbox. Right now this displays on the homepage correctly, and users have the option of selecting multiple “delivery zones” by checking multiple checkboxes next to each zone.
 
However, when I filter for results it returns only those results that match ALL the delivery zones the customer selected.  I would like it to return results that match ANY of the delivery zones the customer selected. 
 
Essentially, I would like the search tool to use an “or” search for when looking for whether a listing matches the delivery zone parameter rather than the “and” search.
 
Doing a bit of research it looks like this is managed using flying sphinx’s search function, and in particular using the argument :with_all.  This is found on line 282 of the listing.rb.
 
In the existing code, :with.all is set as with_all.  Looking a few more lines up, to lines 261 and 265, with_all seems to be an array of all the custom dropdown field options, and the custom checkbox field options.
 
My question, is there simple syntax I could use to let the search function know I want it to return all listings that match any of the checked checkboxes? 
 
Sphinx provides some documentation about this at the below link (scroll about 1/3 of the way down the page, or control+f for “AND and OR”), but I’m having trouble getting the syntax right in this implementation.
 https://pat.github.io/thinking-sphinx/searching.html

Thank you.

**Comment by rap1ds** [comment]
Hi!

As you said, the "Checkbox group" indeed works as a AND search. Instead, the "Dropdown" works as a OR search.

To my understanding, if you pass an array to the `with_all`, if will perform an AND search. If you pass it an array of array, then it will perform OR search.

If you use a debugger (binding.pry) it's easy to see the content of the `with_all` hash. For example, here I have 4 filters, 2 dropdown filters and 2 checkbox filters and the content for `with_all` is:

```
[1] pry(Listing)> with_all
=> {:custom_dropdown_field_options=>[[9, 11], [13, 14]],
 :custom_checkbox_field_options=>[2, 10, 15, 16, 17]}
```

So this means that listing is a match is it hash:

9, 13, 2, 10, 15, 16, and 17 OR
9, 14, 2, 10, 15, 16, and 17 OR
11, 13, 2, 10, 15, 16, and 17 OR
11, 14, 2, 10, 15, 16, and 17

You should also check the HomepageController. The parameters for the Listing.find_with are constructed there. In case of checkbox, it seems that `flatten` is called in order to make the array flat (and perform AND search). The solution could be simple as removing the call to `flatten` in HomepageController (I didn't test it)

Btw. I'm curious to know what is the real world use case for this? To me it doesn't sound very realistic, that if the buyer lives for example in New York, she still wants to search companies that deliver to New York OR Chicago OR San Francisco? I'm asking this because we have had long discussions whether it should be AND search or OR search or maybe something that the admin can choose. We haven't really figured out very good real world use cases where it definitely should be OR search. AND search seems to cover 99% of use cases.

**Comment by chase221** [comment]
Thanks for the help.  I did make the change and the search is now working as I want.  I removed flatten and also changed "checkbox_filter_option" to "filter_option".

The real world case is we have various service zones (based on neighborhood, not city).  When a merchant posts a listing we want them to be able to select however many service areas they want to cover.  This could be one or many areas.  However, in the off case a buyer searches for more than one zone, we want them to see a list of all applicable merchants delivering to any of the zones they selected.
