### ISSUE TITLE
Product post for Users without payment information input

### ISSUE THREAD

**Issue by chase221** [sharetribe/sharetribe#1294]
I am setting up a new marketplace.  We have braintree payments configured and that is working well.  The checkout process is great!

I like the functionality on the hosted version of sharetribe where users can post listings even if they have not yet entered their payment information.  

I am having trouble re-creating this on the OS version though.  Currently when a user attempts to post listings without payment information entered they are directed to the following message:

"You need to fill in payout details before you can post a listing. Go to payment settings to fill in the details."

This message can be removed by changing the transation_processes table process field to "none".  However, this removes the payment functionality from listings and users who have entered their payment information.  Is there a way to set up two transaction processes (one for users who have entered payment information and one for users who have not)?

It would be greatly appreciated if I could get some guidance on the best way to go about doing this.

Thank you.

**Comment by rap1ds** [comment]
The possibility to post before entering payment information has not been implemented to Braintree. If you want to allow it, it requires some work on the code side. I can give you tips what to look at:

In the ListingsController you can find a method `payment_setup_status`. You can see that there's a varaible `can_post` which controls whether the user is able to post listings without payment information. So that's a good place to start to dig deeper. However, I'm pretty sure that there are a lot of places where changes are required.

Keep in mind that Braintree is actually something we have been considering to remove altogether (or at least completely rewrite it, if we decide to keep it in the future). Braintree's Marketplace API is only available in US and in addition, you need to have US company ID in order to register a real Braintree account, so it's not serving us very well.

**Comment by chase221** [comment]
Thanks for the help with this.  We did get the posting ability up and running before the payment details were entered by adjusting the can post section.

**Comment by kaoboyandy** [comment]
Hi, is the above payment gateway issue the case for Stripe?

**Comment by rap1ds** [comment]
@kaoboyandy We don't have Stripe implementation in Sharetribe.

**Comment by kaoboyandy** [comment]
thanks @rap1ds 
What i meant was that if the payment on the platform is stripe, how would I allow user to post a listings before having Stripe info setup? Is it the same process as you mentioned above, if so can you elaborate further? Thank you so much, really appreciated

**Comment by rap1ds** [comment]
@kaoboyandy That depends completely on the implementation of the Stripe integration. Most likely it's not the same process as mentioned above.

I'm sorry but I'm not able to give any better tips than "just implement it so that Stripe setup is not required for posting the listing". :)
