### ISSUE TITLE
support for PostgreSQL

### ISSUE THREAD

**Issue by elf-pavlik** [sharetribe/sharetribe#13]
it looks like at this moment schema doesn't load if I try using PostgreSQL...

```
$ rake db:schema:load
...
-- add_index("communities_listings", ["listing_id", "community_id"], {:name=>"communities_listings"})
rake aborted!
PG::Error: ERROR:  relation "communities_listings" already exists
```

any strategic reason for not supporting databases other than MySQL?

**Comment by younes0** [comment]
I quickly tried to support pgsql, found those issues:
- in schema definition, a lot of index have the same name but for different tables, it's fine for mysql, but not postgresql where index names are specific to one table.
- there's lot of queries that fail because of the conversion CHARACTER VARYING = 1

**Comment by Rex-am-I** [comment]
> I quickly tried to support pgsql, found those issues:
> 
> * in schema definition, a lot of index have the same name but for different tables, it's fine for mysql, but not postgresql where index names are specific to one table.
> * there's lot of queries that fail because of the conversion CHARACTER VARYING = 1

younes0 - did you ever get it to work with PostgreSQL after you identified these issues?

**Comment by younes0** [comment]
@Rex-am-I I can't remember sorry
