### ISSUE TITLE
add new payment gatway

### ISSUE THREAD

**Issue by Amenocy** [sharetribe/sharetribe#1324]
hi 
i want to add new payment gateway to this amazing software , 
in files there are many paypal files in folders such as : controllers , models and services
please help me some to add new gateway

**Comment by math29** [comment]
Do you mean that you want to configure Breantree by adding a new row in the payment gateway table ?

**Comment by rap1ds** [comment]
Hi!

By no means, adding a totally new payment gateway is an easy thing to do. It requires some extensive Ruby skills. Just a word of warning.

The best way to get started is to look how PayPal is implemented. In addition to typical MVC Rails setup, our application uses API and Store layer in order to add some modularity. API and Store form a Service.

Transactions are handled by the TransactionService. The TransactionService then calls appropriate payment service e.g. PaypalService. If you want to build a new payment gateway, the way to go is to make another Service which is then used by the TransactionService.

PayPal is a pretty complex payment gateway, so I guess your integration will be a lot simpler than the existing PayPal integration.

There are also two other payment gateways (Braintee and Checkout Finland), but I wouldn't recommend to learn from those examples, since the code may be some what outdated.
