### ISSUE TITLE
Nokogiri bundle install problem

### ISSUE THREAD

**Issue by diblex** [sharetribe/sharetribe#1337]
Following the instructions to install sharetribe on Ubuntu 14.04, you come to an error where you can't run successfully `bundle install` Nokogiri complains about lib dependencies. I found a workaround, but I am worried this is not explained in the Readme file, so just suggesting to add some comments on it. The solution is: 
- Install nokogiri dependencies: `sudo apt-get install libxslt-dev libxml2-dev`
- Tell nokogiri to use the previous libraries `bundle config build.nokogiri --use-system-libraries`
- Then `bundle install`

**Comment by bingxie** [comment]
This is useful.

**Comment by lfgranja** [comment]
This was useful for me.

**Comment by rap1ds** [comment]
Hi!

What we're the instructions you were following? Some time ago, we removed installation instructions for Ubuntu from our README, since the Sharetribe team is using mainly MacOSX for development and Heroku for hosting. As you may guess, the old installation instructions were pretty bad and outdated because no one from the team had an incentive to keep them updated.

If you have good installation instructions for Ubuntu, we'd be happy to add a link to our README to those instructions!

**Comment by karibuTW** [comment]
Hi guys,

One of my readers posted a comment on freedif.org to share this great project and to ask for a tutorial.

I've written a tutorial for Debian (Should work for Ubuntu too). Here is the link:
http://freedif.org/sharetribe-opensource-market-platform/

Hope it will work like a charm.

Thank you
