### ISSUE TITLE
Production AWS : Can't access to subdomain

### ISSUE THREAD

**Issue by math29** [sharetribe/sharetribe#1366]
Hi everyone !
I am trying to set Up ShareTribes on my AWS EC2/S3/RDC following this tuto : http://www.pequi.eu/installation-de-sharetribe-sur-amazon-web-services-aws-etape-2-parametrage-de-sharetribe/#comment-171

Now I have this : 
- domain : ec2-54-148-232-246.us-west-2.compute.amazonaws.com
- subdomain example (name entered when I logged in ec2-54-148-232-246.us-west-2.compute.amazonaws.com:3000 the first time)
- community_not_found_redirect: "http://ec2-54-148-232-246.us-west-2.compute.amazonaws.com"

The problem is from now I can only access to ec2-54-148-232-246.us-west-2.compute.amazonaws.com:3000 but not to my subdomain where my site is example.ec2-54-148-232-246.us-west-2.compute.amazonaws.com:3000.

Did I miss something ? :)

**Comment by rap1ds** [comment]
Hi!

Check these database columns:

* communities.deleted : Make sure it's `false` (or `0`)
* community_plans.expires_at : Make sure it's `NULL`, so that you "plan" doesn't expire
* community_plans.plan_level : Set to `4`, so that you unlock all the goodies :)

If it still doesn't work, try this:

* Set your `domain` in the config.yml file to: `us-west-2.compute.amazonaws.com`
* Set your `communities.ident` (i.e. the subdomain) to `ec2-54-148-232-246`

Hope that helps!

PS. My French is not very strong, so I can not comment on the instructions there 😉🇫🇷

**Comment by math29** [comment]
Thanks a lot,
I have set my own domain name (Alias with AWS Route 53 etc..) and i deleted in the database the communities.ident. I think I don't need a subdomain.
It looks working for the moment !

**Comment by rap1ds** [comment]
When you say that _"community".trymyhome.xyz steel not accessible._ what do you see if it's not available? Do you see a page saying "Community not found", or is the browser just saying that the page is unavailable.

If you see "Community not found", that means that the request is successfully coming to the Rails application. In this case, the community.ident/community.domain/domain in the config.yml is probably from.

If the browser just can not access the site, then it might be that you have to configure DNS/Firewall or something like that.

Btw. make sure you use the right port (3000? 80?)

**Comment by math29** [comment]
Thank you very much for your help,

That was a just a little DNS mistake ..

Every things works perfectly wright now !
