### ISSUE TITLE
Sidekiq integration

### ISSUE THREAD

**Issue by timchunght** [sharetribe/sharetribe#1420]
Hi,

Good work and I have been tracking the project since its debut. I am wondering if you guys will be considering Sidekiq as a replacement for delayjobs. Thank you.

Best,
Tim

**Comment by rap1ds** [comment]
Hi!

Replacing delayed jobs with something that is based on Redis (Resque, Sidekiq) would probably give some performance benefits, so yeah, it would be nice to replace delayed job with something faster in the future.

However, that's not in our near future roadmap. We have a lot of other stuff to do I think this change is more a "nice to have" than a "must have" thing :)

In addition, since Sidekiq is using threads, it would require some additional work, since all Sharetribe code is not thread safe.

Do you have any additional information about replacing Delayed Jobs with Sidekiq? Do you think that's something we should do in the near future?

I'm closing this issue, since this is not an issue that needs immediate action. However, feel free to post additional comments. I'd like to hear your thoughts!
