### ISSUE TITLE
How can i use Paypal in open source version

### ISSUE THREAD

**Issue by eltonokada** [sharetribe/sharetribe#1462]

**Comment by rap1ds** [comment]
The hosted version uses PayPal as the payment processor. Sharetribe has negotiated a deal with PayPal that allows marketplace administrators to easily start using online payments in their marketplace.

The open source version has the same source code as the hosted version, but due to the agreement with PayPal, using the PayPal integration is not possible with the open source version. Payments in the open source version are handled by Braintree Marketplace, which currently only works in the US. The core team is no longer developing the Braintree integration, and the integration might be removed from future versions of Sharetribe. If that happens, you can continue using a version of Sharetribe that includes Braintree payments.

The current PayPal implementation relies on the deal we have negotiated with PayPal (we have an API key that allows us special privileges). So, to use PayPal in open source version you have two possibilities: 1) Try to negotiate the same deal (might be impossible) 2) Build your own PayPal integration.

Building your own PayPal integration requires strong knowledge on Ruby on Rails and PayPal APIs. However, if you are planning to host only one marketplace in your open source version, the implementation might be actually a lot simpler than the one that is already implemented. The current implementation supports multiple marketplaces hosted on the same service.

We have also planned to extract the PayPal integration to a separate service. That service could be also used by the open source installations (probably with an API key and a small fee for each transaction). However, that's only a plan for the future and we don't know when we will do that.

**Comment by rap1ds** [comment]
I closed the ticket since it's not a bug in Sharetribe code, but feel free to continue discussion on this thread.

**Comment by djcf** [comment]
Thank you for your valuable feedback rap1ds. Has anyone else managed to implement this integration?

**Comment by hubikz** [comment]
@djcf maybe it's to late but here you will find step by step manual http://publish.yexperiment.com/post/156715320289/sharetribe-paypal-payments-the-lost.

We were able to run PayPal on production but with some limitations.
