### ISSUE TITLE
Is it ok (edit: to ask question about own installation here)?

### ISSUE THREAD

**Issue by emilnikkhah** [sharetribe/sharetribe#1536]
HI 
Is it ok to ask question about own installation here?
Regards 
Emil

**Comment by rap1ds** [comment]
Hi @emilnikkhah 

Thanks for asking!

**If you are following the installation steps and installing Sharetribe on Mac OSX or Heroku** then it's totally ok to ask question about your own installation. The core team uses Mac OSX for development and Heroku for production, so those are the "officially" supported platforms.

**If you are installing Sharetribe on Windows/Linux machine or VPS**, then, well... that's a little bit of a gray area. The core team is probably unable to answer to your questions, so that's why we usually encourage people to join the [developer chat at Flowdock](https://www.flowdock.com/invitations/de227bdbe48d24c31a6b749933d3b4eca82e307c). We are planning to setup a mailing list/discuss forum for users how are using the OS versions, but since that's not yet up and running, you will not be "punished" (or anything like that) if you post a question here about the installation :) I will probably close the issue rather soon (because it's not an open bug, probably), but it doesn't prevent people from discussing and answering to your question.
