### ISSUE TITLE
Private message in Arabic language are not displaying properly.

### ISSUE THREAD

**Issue by bipashant** [sharetribe/sharetribe#1537]
Hello
I just installed the fresh copy of Sharetribe on local machine. Everything is working as expected.Thank you all for contributing in such a awesome marketPlace.hats off guys !!!

but one thing I found is private message are not displaying properly in the Arabic language.

here is the snapshot

![screen shot 2015-11-10 at 11 02 52 am](https://cloud.githubusercontent.com/assets/5179884/11055070/4a380c4e-879b-11e5-9d3a-3d02c2b7aed0.png)

but it is working fine for English language.

![screen shot 2015-11-10 at 11 02 25 am](https://cloud.githubusercontent.com/assets/5179884/11055102/964930e0-879b-11e5-9931-e68f9cd8cdcf.png)

I'm not sure  whether it is an issue with code or my local system.
thank you :)

**Comment by rap1ds** [comment]
Hi @bipashant !

Thanks for reporting the issue!

Unfortunately, the current version of Sharetribe doesn't have a good support for right-to-left languages. This is something that we will not fix for the current version, since it would require a lot of work to the front-end code.

We have already plans to rebuild the front-end code. When this happens, we will keep RTL support in mind.

**Comment by bipashant** [comment]
@rap1ds 
thanks for quick review
I really appreciates your effort. 
You guys are awesome. :)

**Comment by probar** [comment]
Any change in the status of RTL language support ?

**Comment by thomasmalbaux** [comment]
Hi there!

No update at this point. This isn't something we are working on but we'll of course mention it in [release notes](https://github.com/sharetribe/sharetribe/releases) if we move forward with this suggestion.
