### ISSUE TITLE
Email confirmation error on staging environment

### ISSUE THREAD

**Issue by priviterag** [sharetribe/sharetribe#1724]
I'm trying to deploy on a staging server (e.g. staging.domain.com) and I get an error when I register: 
```
App 23619 stdout:
App 23619 stdout: TypeError (no implicit conversion of nil into String):
App 23619 stdout:   app/models/email.rb:64:in `send_confirmation'
App 23619 stdout:   app/controllers/confirmations_controller.rb:35:in `create'
App 23619 stdout:   lib/rack_middleware/custom_domain_cookie.rb:20:in `call'
App 23619 stdout:
```
after further investigation, it seems that the community is nil. What is the recommended way to deploy using the subdomain to identify the environment and not the community?

**Comment by rap1ds** [comment]
Hi @priviterag 

I'm not sure if I totally undestood the question. Can you tell me a bit more about your setup?

Did I understand right, you're having two environments (two server processes), one which is e.g. production environment and one which is staging environment. Those are running in production.domain.com and staging.domain.com and you'd like to identify the environment from the subdomain. In that case, I guess you should set your DNS to point to correct servers. Or did I miss something?

I'm closing this issue since it looks that this is not an issue in the Sharetribe codebase. However, feel free to continue the discussion in this thread.
