### ISSUE TITLE
Connection pool problems in production with webrick and puma

### ISSUE THREAD

**Issue by woto** [sharetribe/sharetribe#1763]
##### Sharetribe Version:
c0a21707adc57b5859d90ac6e915e1803a4b240d

##### Environment:
Ubuntu 15.04

##### Server mode:
production mode

##### Description:

Hi, it seems that's i stumbled upon problem described in this articles 
http://stackoverflow.com/a/27072918/237090
https://bibwild.wordpress.com/2014/07/17/activerecord-concurrency-in-rails4-avoid-leaked-connections/
When i accessing non existent page then connection in mySQL stale (viewing with ```show processlist``` ) I'm able make requests to non existent pages exactly equal times as described in config/database.yml next i'm getting ```ActiveRecord::ConnectionTimeoutError (could not obtain a database connection within 5.000 seconds (waited 5.000 seconds)):```

When i'm totally commenting ErrorsController the problem goes away.

puma webserver adds additional information about error ```Error during failsafe response: could not obtain a database connection within 5.000 seconds (waited 5.000 seconds)```

**Comment by woto** [comment]
Not sure that this 100% good solution, but it definitely works for me.

```ruby
diff --git a/app/controllers/errors_controller.rb b/app/controllers/errors_controller.rb
index 820eeed..0e84e84 100644
--- a/app/controllers/errors_controller.rb
+++ b/app/controllers/errors_controller.rb
@@ -35,7 +35,11 @@ class ErrorsController < ActionController::Base
   private
 
   def current_community
-    @current_community ||= ApplicationController.find_community(community_identifiers)
+    Thread.new do
+      ActiveRecord::Base.connection_pool.with_connection do
+       @current_community ||= ApplicationController.find_community(community_identifiers)
+      end
+    end
   end
 
   def community_identifiers
```

**Comment by rap1ds** [comment]
Hi @woto 

Thanks for reporting the issue!

Currently, we don't recommend you to run Sharetribe in a multithread server such as Puma. We haven't tested Sharetribe with multithreaded servers and we can't promise that everything is thread-safe (actually we know that everything is not thread safe). We recommend you to use something like Passenger or Unicorn instead.

I'm closing this issue because we don't officially support Puma. However, feel free to continue the discussion in this thread. If you find a fix, I'm happy to have a look at the Pull Request.

**Comment by woto** [comment]
Yea, i found solution. But it looks ugly.
I told you that i also getting problem in webrick, which is not multithreaded.
I found in Internet that somebody wrote that this problem exists because of closing connection before middleware execution.

```ruby
diff --git a/app/controllers/errors_controller.rb b/app/controllers/errors_controller.rb
index 820eeed..1ba4b12 100644
--- a/app/controllers/errors_controller.rb
+++ b/app/controllers/errors_controller.rb
@@ -35,7 +35,11 @@ class ErrorsController < ActionController::Base
   private
 
   def current_community
-    @current_community ||= ApplicationController.find_community(community_identifiers)
+    thread = Thread.new do
+      ActiveRecord::Base.connection_pool.with_connection do
+       @current_community ||= ApplicationController.find_community(community_identifiers)
+      end
+    end.join
   end
 
   def community_identifiers
@@ -44,11 +48,17 @@ class ErrorsController < ActionController::Base
   end
 
   def title(status)
-    community_name = Maybe(@current_community).map { |c|
-      c.name(community_locale)
-    }.or_else(nil)
-
-    [community_name, t("error_pages.error_#{status}_title")].compact.join(' - ')
+    result = ''
+    thread = Thread.new do
+      ActiveRecord::Base.connection_pool.with_connection do
+        community_name = Maybe(@current_community).map { |c|
+          c.name(community_locale)
+        }.or_else(nil)
+
+        result = [community_name, t("error_pages.error_#{status}_title")].compact.join(' - ')
+      end
+    end.join
+    result
   end
 
   def community_locale
```

**Comment by rap1ds** [comment]
@woto Oh, sorry I missed the webrick part!

Thanks for the diff.

**Comment by kimroen** [comment]
We ran into this issue, running Puma in single-thread mode. For other people finding this, we solved it based on the diff above from @woto (thanks!), but we found that creating threads is not necessary.

Our `current_community` and `title`:

```rb
def current_community
  ActiveRecord::Base.connection_pool.with_connection do
    @current_community ||= ApplicationController.find_community(community_identifiers)
  end
end
```

```rb
def title(status)
  result = ''
  ActiveRecord::Base.connection_pool.with_connection do
    community_name = Maybe(@current_community).map { |c|
      c.name(community_locale)
    }.or_else(nil)

    result = [community_name, t("error_pages.error_#{status}_title")].compact.join(' - ')
  end
  result
end
```

As suggested by the various resources out there, the issue comes up because of the use of tip 3 in [this article](http://blog.plataformatec.com.br/2012/01/my-five-favorite-hidden-features-in-rails-3-2/) (`config.exceptions_app = self.routes`).

This only happens when loading something that would be a 404, with `config.consider_all_requests_local` set to `false`, like it is in production.
