### ISSUE TITLE
Google Analytics not working for production instance

### ISSUE THREAD

**Issue by ankurj77** [sharetribe/sharetribe#1950]
##### Sharetribe Version:
v5.6.0

##### Environment:
Google Cloud Server - Ubuntu
Linux 3.19.0-56-generic #62~14.04.1-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux

##### Server mode:
Production

##### Description:
When I check sessions and visits information in my GA account, I don't see any activity. There are at least 100 visitors. I also checked for GA script and network activity on all pages, but I don't see any visit event being posted to Google Analytics.

##### Steps To Reproduce:
Put the tracking ID from Google Analytics account into the sharetribe admin page - /en/admin/communities/1/analytics

Expected result: Sessions and visits being traceable in GA.

Actual result: No visits or sessions being observed in GA.

**Comment by rap1ds** [comment]
@mporkola Do you know about this?

**Comment by ankurj77** [comment]
I looked at the code and found out that the [file ](https://github.com/sharetribe/sharetribe/blob/v5.6.0/app/views/layouts/_google_analytics_script.haml) checks analytics configuration at two different places. It first checks for config.yml and then also checks for @current_community.google_analytics_key. I am not sure what are those two analytics options.

I got it working by enabling analytics from config.yml. But I am not sure why it shouldn't have worked from admin panel?

**Comment by mporkola** [comment]
The `config.yml` setting is about whether to use Google Analytics at all. The admin panel configuration (`@current_community.google_analytics_key`) is where marketplace admin can set their own GA key, so each admin can have their own analytics in a multitenant installation such as sharetribe.com. If you're running this just for yourself, you can also set the GA key in `config.yml` with `google_analytics_key` instead of admin panel.

**Comment by ankurj77** [comment]
Thanks, that clarifies :)
