### ISSUE TITLE
Valid OAuth redirect URIs while creating facebook app to enable facebook login

### ISSUE THREAD

**Issue by bipashant** [sharetribe/sharetribe#2014]
##### Description:

Hi, I'm trying to enable facebook login. I've created an facebook app and added the credentials in the admin panels but while trying to login with facebook, I got the following response in server log. 

`
App 15014 stdout: (facebook) Authentication failure! invalid_credentials: OAuth2::Error, : 
App 15014 stdout: {"error":{"message":"Error validating verification code. Please make sure your redirect_uri is identical to the one you used in the OAuth dialog request","type":"OAuthException","code":100,"fbtrace_id":"CK1P4ZLUHR2"}} 
`

I tried everything like `xyz.com`,  `www.xyz.com`,  `http://xyz.com`,  `http://www.xyz.com`,  `http://www.xyz.com/` in the OAuth redirect urls but nothing worked for me.

I can't even skip this field now  as I were skipping this before in some other project. Would someone please mention what is the valid url in order to solve the issue.
Thanks

**Comment by thefoodcorridor** [comment]
Looks like you need a `/` at the end of the url, at least you did in 2012.

http://www.seifeet.com/2012/10/facebook-authentication-error-error.html

**Comment by bipashant** [comment]
@rap1ds 
Would you please see this issue once.
Thanks

**Comment by rap1ds** [comment]
@bipashant Here's a link to a Knowledge Base article that has step-by-step guide how to setup Facebook login. I hope this helps: http://support.sharetribe.com/knowledgebase/articles/412490

**Comment by bipashant** [comment]
@rap1ds 
I've followed the above article but still getting the same error.

> App 11114 stdout: (facebook) Callback phase initiated.
> App 11114 stdout: (facebook) Authentication failure! invalid_credentials: OAuth2::Error, : 
> App 11114 stdout: {"error":{"message":"Error validating verification code. Please make sure your redirect_uri is identical to the one you used in the OAuth dialog request","type":"OAuthException","code":100,"fbtrace_id":"HuFMrKZyhiH"}}

**Comment by rap1ds** [comment]
I'm not aware of anything else you should do in addition to this.

Quick Googling gave two leads:

1) As @thefoodcorridor mentioned, it seems that many people have had the issue with too many or too few slashes: http://stackoverflow.com/questions/16562602/facebook-redirect-url-issue-oauthexception

2) What's the Sharetribe version you are using? Make sure you use 5.2.0 or newer, since omniauth-facebook gem [had an issue in the earlier versions](https://github.com/mkdynamic/omniauth-facebook/issues/220).

**Comment by bipashant** [comment]
Finally, solved the issue myself,
I've added following line under  the SessionsController -> facebook_setup method

``` request.env["omniauth.strategy"].options[:callback_url] = http://www.xyz.com/people/auth/facebook/callback" ```

and it is working fine. I really appreciates your collaboration :)

**Comment by rap1ds** [comment]
Hmmm... I'm wondering why this isn't an issue in our hosted sharetribe.com. My guess is that the `http://www.xyz.com/people/auth/facebook/callback` is actually the same as the default callback_url, but for some reason the default is not correctly working in your setup.

**Comment by rap1ds** [comment]
Anyway, good that you got it solved!

**Comment by Warond** [comment]
Guys, I have a big problem. I had an Instant Article,.. and I tried to add another Facebook Page to the my Instant Article. When I came back, nothing was the same. I deleted that page meta tag and now I got this msg:

URL Blocked: This redirect failed because the redirect URI is not whitelisted in the app’s Client OAuth Settings. Make sure Client and Web OAuth Login are on and add all your app domains as Valid OAuth Redirect URIs.   (when I put https://___________.com/login/callback)

When I put just (https://_________.com, I got the msg - in the attachment.
![instant articles problem](https://cloud.githubusercontent.com/assets/20108160/16300044/9b0e64c8-3935-11e6-85ac-6929c5729cb2.jpg)

Can someone help me - what to do?

Also, when I created a new app, I got the msg from attachment.

I use Instant Articles Facebook Instant Articles. My site is built in the Wordpress.

Kind Regards,
Warond

**Comment by taismatos29** [comment]
hi, i also have a problem with my facebook login,....

maybe someone could help me
i created an App, but it says I have to add javascript to my HTML but i have no idea how to  make it.
the twitter login was  easy and didnt require any code..


how to do it?

thanks

**Comment by thomasmalbaux** [comment]
Hi @taismatos29 !

Did you follow the instructions at https://help.sharetribe.com/managing-your-marketplace/social-media/how-to-configure-facebook-connect? If yes, you shouldn't have to add any JS code at all, just input your API keys and it should work fine.

Can you have a look and follow very closely the instructions above? This should then work smoothly!

**Comment by invinayak** [comment]
Hi may i know can we pass query string in call back url ? like example 
http://www.xyz.com/people/auth/facebook/callback?userid=

**Comment by shamimmoeen** [comment]
Hi @invinayak, did you find any way?

**Comment by invinayak** [comment]
Hi @shamimmoeen I found a way to pass value from the property we have called a state , what value we wanted to pass from query string we can pass from this State
