### ISSUE TITLE
Add sitemap support

### ISSUE THREAD

**Issue by mooreds** [sharetribe/sharetribe#2204]
This may be more of a feature request, so feel free to close, but I'd love sitemap support, even if it was just listings.  This gem looks helpful: https://github.com/kjvarga/sitemap_generator

**Comment by mooreds** [comment]
Whoops, I see that this is already a feature request: http://support.sharetribe.com/forums/240322-sharetribe-development-ideas/suggestions/7103653-add-a-sitemap-xml-file-to-marketplace

**Comment by mooreds** [comment]
Would y'all be amenable to a PR adding this feature for listings only?

@rap1ds ?

**Comment by rap1ds** [comment]
I'm not very familiar with sitemaps (and SEO stuff in general). @thomasmalbaux what do you think? Should we have a sitemap support?

**Comment by thomasmalbaux** [comment]
Hey there! Thanks for the suggestion. Adding a sitemap would definitely make sense and would be a great addition!

This probably requires a bit of thinking though, as such sitemap should be updated as soon as listings are opened or closed.
Same thing with new users (when they create/delete their profiles) and categories (that can be updated). Even though I understand that it wouldn't be part of a first version, which might make sense).

Adding static pages ("About/Terms/..." pages) would probably be quite easy and would make sense, on top of listings.
The `<priority>` and `<changefreq>` tags could also be discussed to be relevant enough (for example for static pages).
Finally there might be some challenges with pictures and assets, but they maybe could be left out of a first sitemap version.

Again overall, this would definitely be a great improvement! As you mentioned @mooreds it has been mentioned a few times by Sharetribe users and sitemaps are key for SEO to help content discovery.

Happy to continue this discussion a bit (even though I couldn't help with technical details) if you are interested to consider this feature.

**Comment by mooreds** [comment]
A bigger question for me is how to do this for the open source solution and at the same time make it worth with the different communities.  Maybe the default sitemap url is pulled from the community?

As far as pages, I hear you about the complexities.  For a first pass, I'd just want to get the open listings, and maybe try to do the static pages if it made sense.  

If a listing is closed, does it need to be removed from the sitemap immediately, or could it wait for a day?  I'd definitely suggest a daily task to rebuild the sitemaps, rather than rebuilding them on demand.

**Comment by mooreds** [comment]
Hi folks,

I did this for my local version of sharetribe (based off of 5.6, though I plan to keep it up to date).

It involved a new gem, a new controller, a new config file, and a couple of rake tasks.

If this is of interest, please let me know.  Am happy to submit a PR, or whatever.

Here's the gist I followed for the rake tasks.
https://github.com/kjvarga/sitemap_generator/wiki/Uploading-the-sitemap-to-S3-with-paperclip,-aws-s3-and-aws-sdk

**Comment by mooreds** [comment]
I actually just wrote a blog post about this: http://www.mooreds.com/wordpress/archives/2215 (for anyone else who is looking).

**Comment by rap1ds** [comment]
@mooreds Cool! Right now we are in a middle of a deadline pressure, but I'll have a look at your gist in couple days.

**Comment by rap1ds** [comment]
Hi @mooreds ! I finally had time to read your blog post and the gist you linked. Good stuff! 👍 

Sitemap would be a nice addition to Sharetribe. We are definitely interested to merge it if you are willing to contribute! 

However, there are few things that needs to be taken into account in the multi marketplace setup:

Adding rake task + scheduler + s3 upload brings some complexity, that hopefully could be avoided somehow. In addition to the complexity, the hosted sharetribe.com hosts tens of thousands marketplaces (most of them are inactive, though), so running a scheduler everyday to build a new sitemap and upload it to S3 for each marketplace sounds like a massive job and it probably takes too much of the workers time.

If the performance of fetching the information from database and rendering the sitemap is good enough (say, less than 200ms), I would suggest doing that during the request in the controller. Of course, rendering the sitemap over and over again per each request is not feasible, but we could setup CDN in front of that controller action and set the cache time to 1 day. For OS installation, the CDN setup might be too heavy in the beginning, so there could be a configuration flag which defines whether CDN is in use or not. Here's a pseudo-code example:

```ruby
# config/routes.rb
get "sitemap.xml.gz" => "sitemaps#sitemap", format: :xml
get "sitemap/generate" => "sitemaps#generate", format: :xml
 
# app/controllers/sitemaps_controller.rb
class SitemapsController < ApplicationController
  def sitemap
    if <cdn is in use>
      redirect_to <cdn address> # The CDN then fetches the sitemap.xml from the sitemap/generate URL which points to the `generate` action
    else
      render_site_map
  end

  def generate
    render_site_map
  end

  private

  def render_site_map
    cache do
      <site map rendering code here>
    end
  end
end
```

How does that sound to you?

Btw. when search engines try to fetch the `www.yourdomain.com/sitemap.xml`, are you sure they follow redirects? Even to different domains? I didn't find anything about this from sitemaps.org

**Comment by mooreds** [comment]
> Btw. when search engines try to fetch the www.yourdomain.com/sitemap.xml, are you sure they follow redirects? Even to different domains? I didn't find anything about this from sitemaps.org

@rap1ds Well, google found the sitemap for my site, so I think that is OK (though perhaps not optimal).  Here's an answer from the internet: http://webmasters.stackexchange.com/questions/28124/can-i-host-a-sitemap-on-another-domain

Re: your solution, makes total sense.  Unfortunately the sitemap gem I used doesn't have an adapter to output not to a file.  I imagine it wouldn't be hard to do so (based on the existing adapters here: https://github.com/kjvarga/sitemap_generator/tree/master/lib/sitemap_generator/adapters but obviously that would add more--I'd have to get the adapter added into that gem, or fork it.

What if I added a 'community' switch to the rake task?  Or would that still be prohibitive for sharetribe.com?

**Comment by rap1ds** [comment]
The `sitemap_generator` gem seems to be a bit problematic for multi marketplace setup in two ways:

1. As you mentioned, there's no adapter to just return the string output
1. Configuring `default_host` seems to be a global configuration. In multi marketplace setup this needs to be changed dynamically.

But, I guess both of those problems can be solved:

### 1. String output

Based on this blog post (http://blog.arkency.com/2014/02/sitemaps-with-a-bit-of-metal/), it seems to be pretty easy to add a new custom adapter.

### 2. Configuring `default_host` on runtime

The Sitemaps controller should configure the `default_host` on runtime. It can be done, but it's a bit risky since `SitemapGenerator::Sitemap.default_host` is a global configuration and thus not thread safe. Ok, admittedly we're not running Sharetribe on multi-threaded server, but hey, Rails 5 has Puma as a default server, so definitely Rails is going to that direction and that's why it's wise to try to make the code as thread-safe as possible, even if threads are not our headache today.

Anyway, the [Sitemaps with a bit of Metal](http://blog.arkency.com/2014/02/sitemaps-with-a-bit-of-metal/) blog post seemed pretty good. Also, using Metal controller for this is a good idea in my opinion 👍 . We don't need to full set of `ApplicationController` methods to render the sitemap. Our newest Landing page feature is also using Metal controller: https://github.com/sharetribe/sharetribe/blob/master/app/controllers/landing_page_controller.rb

I'm not sure if I completely understood what you meant with a "community" switch? Do you mean that there would be a switch which would enable this feature only for OS installations?

**Comment by mooreds** [comment]
@rap1ds I think you've mapped out a good path forward.  Let me see what I can get done this week.

**Comment by rap1ds** [comment]
I'm closing this issue now. Please follow PR #2303 for more information.
