### ISSUE TITLE
Elaboration on usage of asset_host and user_asset_host in the config.yml file 

### ISSUE THREAD

**Issue by pcm211** [sharetribe/sharetribe#2439]
##### Sharetribe Version:
Head

##### Environment:

EC2, AWS

##### Server mode:
PRODUCTION

##### Description:

I would request someone to please elaborate the usage and differences in (config.defaults.yml)

asset_host:  &
user_asset_host: 

and its usage (pl update the commented portion too if possible )
which one is to be used and point to upload bucket and which one to normal bucket ...if i am getting it right ....

##### Steps To Reproduce:

Expected result: clearer explanation if possible

Actual result: which cloudfront configs to be used and where to be used --- updated comments in the config.defaults.yml file

**Comment by rap1ds** [comment]
**asset_host:**

Most likely, in production setup, you have a Rails server serving your assets and a CDN, such as Amazon Cloudfront, configured in front of the Rails app. The CDN can then cache and serve the assets so that they are not served directly from the Rails app. Under the hood, the `asset_host` configuration is passed directly to Rails' `config.action_controller.asset_host`. You can read more here: http://guides.rubyonrails.org/asset_pipeline.html#set-up-a-cdn-to-serve-static-assets

**user_asset_host:**

If you use S3 to store user uploaded files (such as listing images), you can configure CDN server in front of your S3 bucket. This way the uploaded files are served faster from the edge servers close to your users. Add the URL of the CDN that is configured in from of the S3 bucket to `user_asset_host`.

Both `asset_host` and `user_asset_host` should have a URL to CDN server. Neither of those should have a URL to your S3 bucket.

**Comment by rap1ds** [comment]
Is there something specific you think should be added to the docs or to the comment in `config.defaults.yml`?

**Comment by pcm211** [comment]
@rap1ds ... yes and since now its clearer to me ....i would help out in a more elaborate commenting of the same 

tx
