### ISSUE TITLE
How many website are base on this project?

### ISSUE THREAD

**Issue by 1c7** [sharetribe/sharetribe#2466]
Can you guys provide a list of website that are base on this project?
Curious about it, 

Thank you very much.

and why open source this project? I didn't get it.

**Comment by pcm211** [comment]
Can you guys provide a list of website that are base on this project? ---- MANY

and why open source this project? I didn't get it. --- So all can contribute and build it better and stronger reduce development budget etc etc ... FYI Linux is an Open source project which has gained a strong foothold over the years ...and is a direct competitor to linux ... had it been closed source ,...  the development & users  would have been limited ..due to lesser no of minds putting their brains on it and using it ....

You can also read about Open source on the net.. to enlighten u further of the imp of open source

i hope this ans all ur queries and closes this

**Comment by rap1ds** [comment]
It's actually impossible to give you a list of projects that is based on Sharetribe. That's the thing with Open Source, you can just download it for free and use it without even telling to us :)

I remember that @thomasmalbaux had somekind of list of couple marketplaces that were running on Sharetribe, do I remember right?

About your last question, why to open source this project. What an interesting question! I pinged @Kusti to write an answer. He'll write an answer to the community forum (www.sharetribe.com/community), since this is an interesting topic to discuss. The community forum is the best place for this kind of discussion. We want to keep the Github issues mainly for bug reports.

**Comment by thomasmalbaux** [comment]
Quite a few marketplaces uses Sharetribe open-source version however we don't track them so there is no complete list of examples to share. But here are a few ones that we've heard about:

- [ShareGrid](https://losangeles.sharegrid.com/)
- [ArtDew](http://artdew.com/)
- [Closay](https://www.closay.dk/)
- [The Food Corridor](https://app.thefoodcorridor.com/)
- [GodtPrestert.no](https://www.godtprestert.no/nb?view=list)

And hopefully over time more and more people will advertize their project in [this dedicated thread](https://www.sharetribe.com/community/t/marketplace-showroom-are-you-hosting-an-open-source-sharetribe-marketplace-advertise-it-here/51) of the Community forum!

**Comment by 1c7** [comment]
@pcm211 
@rap1ds 
@thomasmalbaux 
Thanks for reply! 
very helpful!

**Comment by 1c7** [comment]
Thanks for the MIT license.
We plan to build a website base on sharetribe
:dancer: 
@thomasmalbaux 
@rap1ds

**Comment by Kusti** [comment]
@1c7 I wrote [a blog post](https://medium.com/learnings-in-and-around-sharetribe/why-sharetribe-is-open-source-9462384a2f81#.oiri4ckcm) to answer to the question "Why Sharetribe is open source", check it out.

**Comment by 1c7** [comment]
@Kusti Thank you
