### ISSUE TITLE
Current state of play with Paypal and other payment gateways

### ISSUE THREAD

**Issue by djcf** [sharetribe/sharetribe#2616]
Great software! My team is currently evaluating it for production use. Due to a rather special priority feature (LDAP logins) we have to self-host, so I wanted to check my understanding before reporting back.

I understand [this issue](https://github.com/sharetribe/sharetribe/issues/1395) [has come up a lot](https://github.com/sharetribe/sharetribe/issues/1155) including on the community forum.

Although it could be a matter of [following some steps](https://www.sharetribe.com/community/t/paypal-open-source-integration/288) [to generate an API key with the correct credentials](https://www.sharetribe.com/community/t/general-steps-how-to-integrate-with-paypal-in-community-version/170), I'm not aware of anyone who has succeeded yet. Essentially,

> "Sharetribe has negotiated a deal with PayPal that allows marketplace administrators to easily start using online payments in their marketplace. Payments in the open source version are handled by Braintree Marketplace, which currently only works in the US. The current PayPal implementation relies on the deal we have negotiated with PayPal (we have an API key that allows us special privileges). So, to use PayPal in open source version you have two possibilities: 1) Try to negotiate the same deal (might be impossible) 2) Build your own PayPal integration."

[Source](https://github.com/sharetribe/sharetribe/issues/1462)

So it seems at the moment the technical barriers are prohibitive. Is this assumption correct?

Be that as it may, what other options for payment gateways exist in the community open source version? I understand a lot of interest has been generated in Stripe (though perhaps the Sharetribe devs prefer MangoPay?) but my understanding is that SharePoint does not currently support multiple gateways or offer an extensible architecture for them. If that is the case, how are users currently implementing payments in the open source version?

**Comment by rap1ds** [comment]
> So it seems at the moment the technical barriers are prohibitive. Is this assumption correct?

If I may rephrase this a bit, I'd say that there are no _technical_ barriers. The barrier is PayPal's security process/policy.

Technically, PayPal works out of the box in OS installation **IF** you are able to get a PayPal API key that allows you to do Reference Transactions. But that's a huge "if".

**Why it's so difficult to get a proper API key from PayPal?**

After many lengthy discussions with PayPal's integration consultants, we ended up in an implementation that does following:

Before payment:

1. Seller connects his/her PayPal account
2. Seller grants us permission to do **Reference Transactions**

During the payment:

1. Buyer starts a new transaction and pays via PayPal. At this point we preauthorize the payment.
2. Seller accepts the transactions. Payment is now captured.
3. When payment is completed, **we do another payment, Reference Transaction, where we take the commission from Seller's account without special permission from Seller**

After the Seller has granted us the permission to do Reference transactions, we can make new PayPal payments where we take money from Seller's account without special permission from seller at this point. So, the permission to do Reference Transactions is pretty powerful, and that's why I totally understand why PayPal is not eager to give that permission easily to everyone.

To conclude, the commission payment is the reason why Sharetribe's PayPal integration requires the additional permissions from PayPal. The fact that money is moving between three parties (seller, buyer and marketplace owner) makes the integration a bit difficult. Many other software were money is only moving between seller and buyer, this integration is much simpler and doesn't require special permissions from PayPal.

**So what are your options?**

1. Try to get the permission for Reference Transactions from PayPal.

  I expect this to be difficult, maybe even impossible. I haven't heard anyone (except Sharetribe.com) to succeed in this.

2. Remove the commission functionality from the code

  If you're not interested in collecting the commission, you could remove the commission feature from the code. I haven't tried if this actually works and I except it to be an nontrivial amount of work

3. Implement your own payment gateway

  Stripe, MangoPay, you name it... I've heard that people have successfully implemented Stripe integration, but I've never seen any code. I'd be happy to see some code. Open Source FTW!

4. What until Sharetribe implements other gateways.

  I'm sure that we will add more payment gateways in the future. However, I have no idea when this will happen, nor can I make any promises. It's not currently even in the near term roadmap so I'm pretty sure it's not happening in 2016. Maybe next year...

If you're interested in technical details, see more from here: https://developer.paypal.com/docs/classic/express-checkout/integration-guide/ECReferenceTxns/#billing-agreements

I hope this answer clarified the situation with PayPal, but I'm happy to answer if you have more questions!

I'm going to close this issue now because it's not a bug in Sharetribe code base, however, feel free to continue discussion in this thread.

**Comment by pravipravi** [comment]
Hi Mikko,

I am also interested in this question. Is there any update on integrating PayPal payment gateway with ShareTribe open source?

One of my marketplace accounts got rejected from BrainTree.

**Comment by guilhermedallanol** [comment]
+1

**Comment by ramesh2007** [comment]
HI what about local payment gateways matter like iyzipay is it possible to integrate

Thanks

**Comment by thomasmalbaux** [comment]
Hi again Ramesh!

Indeed right now we don't support Izypay (only PayPal and Stripe). You can build this integration yourself if you want to (this requires some technical knowledge and you can also hire your own team).

You can also discuss this with other open-source users in Sharetribe's Community forum at https://www.sharetribe.com/community/

Hopefully this helps!
