### ISSUE TITLE
Google map marker limited to 125 in number

### ISSUE THREAD

**Issue by ankurj77** [sharetribe/sharetribe#2652]
##### Sharetribe Version:

5.6.0
##### Environment:

Google cloud hosted on Linux OS.
##### Server mode:

Production
##### Description:

I am facing an issue with map markers. They are limited to 125 in number for my website. Sharetribe suggests that the limit is 2000, is there anything I need to do to increase that limit to 2000? 
##### Steps To Reproduce:

The platform has 240 open listings

Expected result: Map view should show 240 markers.

Actual result: Map always show 125 markers

**Comment by pcm211** [comment]
register your self to google and get the map api ..add it to your code in the config file ...

hope this solves the issue ...

*** as the API Calls to google maps is limited for unknown and open users

**Comment by rap1ds** [comment]
@ankurj77 Keep in mind that only listings that have address are visible on the map. Would that be the reason why not all listing are on the map? Maybe there are 115 listings without address?

If that's not the case, then I'd need more information to investigate this problem. Please list exact steps how I can reproduce this issue on my machine, or otherwise I'm not able to investigate this further.

**Comment by rap1ds** [comment]
Closing as inactive.
