### ISSUE TITLE
Payment Integration using Active Merchant gem

### ISSUE THREAD

**Issue by delblues** [sharetribe/sharetribe#2685]
Is it possible to integrate other type of payment gateway using Active Merchant gem, abstracting the TransactionServices api and the Store services?

**Comment by rap1ds** [comment]
Thanks for the suggestion!

In the long run, we are planning to move major part of the transaction logic (incl. payments) away from Rails code base to a separate transaction service, which will be implemented in Clojure. This work has already started: We are currently building a system which will prevent double bookings on rental and service marketplaces, and for that we have some Clojure code built already. Because of that, using Active Merchant is not well aligned with our future plans.

And just to clarify, the new Clojure components will be available to open source users.

**Comment by delblues** [comment]
@rap1ds  Thanks for sharing with us the news! 
So, nowadays, in my understanding, It's possible this abstraction, right?

Could you please explain how transaction services works for the payments flow? 

thank you
