### ISSUE TITLE
Error Installing NPM

### ISSUE THREAD

**Issue by shoaibmalik786** [sharetribe/sharetribe#2730]
Hi Team
I am getting following error in npm install
npm ERR! Linux 4.4.0-45-generic
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v6.9.0/bin/node" "/home/ubuntu/.nvm/versions/node/v6.9.0/bin/npm" "install"
npm ERR! node v6.9.0
npm ERR! npm  v3.10.8
npm ERR! code EBADPLATFORM

npm ERR! notsup Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/tourthatcity/client/npm-debug.log

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 4.4.0-45-generic
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v6.9.0/bin/node" "/home/ubuntu/.nvm/versions/node/v6.9.0/bin/npm" "install"
npm ERR! node v6.9.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! undefined postinstall: `cd client && npm install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the undefined postinstall script 'cd client && npm install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd client && npm install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

Please help

**Comment by kpuputti** [comment]
Which version of Sharetribe are you using?

Could you try updating Node.js to 6.9.1 if that works?

**Comment by shoaibmalik786** [comment]
Hi @kpuputti - Yes the node version is 6.9 as you suggested on official repo, i also tried with 6.9.1 but same error with that also, please suggest me the possible solution.
Thanks

**Comment by mduruisseau** [comment]
Hi !

I have a similar error with the 'npm install' command.
I am on Debian v8, all requirements are installed, and the previous commands work fine, but npm install return some errors: 

> @ postinstall /var/www/sharetribe
> cd client && npm install

npm ERR! 404 Not Found
npm ERR! 404
npm ERR! 404 'customfile-loader' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /var/www/sharetribe/client
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code E404
npm ERR! git clone git@github.com:github:mporkola/storybook-deployer Cloning into bare repository '/home/mick/.npm/_git-remotes/git-github-com-github-mporkola-storybook-deployer-87dfde65'...
npm ERR! git clone git@github.com:github:mporkola/storybook-deployer fatal: remote error:
npm ERR! git clone git@github.com:github:mporkola/storybook-deployer   %s is not a valid repository name
npm ERR! git clone git@github.com:github:mporkola/storybook-deployer   Email support@github.com for help
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/sharetribe/client/npm-debug.log
npm ERR! not ok code 0

npm ERR! @ postinstall: `cd client && npm install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ postinstall script.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd client && npm install
npm ERR! You can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /var/www/sharetribe
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/sharetribe/npm-debug.log
npm ERR! not ok code 0

I tried different solution (alias node => nodejs (for debian), download the package myself, ...) but nothing efficient.

I use the latest version of sharetribe (git checkout latest). 

Could you help me ?

**Comment by 1c7** [comment]
Hi
@shoaibmalik786 
Try upgrade your system package with "apt update" 'apt update' (in this order): 
more info about the difference between 'update' and 'upgrade': http://askubuntu.com/questions/94102/what-is-the-difference-between-apt-get-update-and-upgrade

**Comment by 1c7** [comment]
@shoaibmalik786  your last comment is 11 days ago.
did you solve your problem?

**Comment by rap1ds** [comment]
Inactive. Closing.
