### ISSUE TITLE
Random suggestion: pry-remote for debugging

### ISSUE THREAD

**Issue by jhendley25** [sharetribe/sharetribe#2732]
Hey folks, 

First off, sorry for not using the issues template. This is more of a random Readme suggestion. 

We're running a similar setup with Foreman, and I've had success with [pry-remote](https://github.com/Mon-Ouie/pry-remote) that allows a thread-blocking way to jump into rails and debug and whatnot. I just figured I'd drop it in here since it made my life easier.

**Comment by kpuputti** [comment]
Thanks for the suggestion, we'll try it out!

**Comment by rap1ds** [comment]
Thanks for the suggesting!

I tried `pry-remote` briefly, but it seems that there's an outstanding [issue in pry-buybug](https://github.com/deivid-rodriguez/pry-byebug/issues/33) which prevents `pry-remote` from working :( I tried `pry-remote` without `pry-buybug` and it was working perfectly, but we do want to keep `pry-buybug`.

**Comment by rap1ds** [comment]
@jhendley25 This is a good suggestion, but I'm closing this for now because the [open pry-buybug issue](https://github.com/deivid-rodriguez/pry-byebug/issues/33) seems to be a show stopper.

Let's keep on eye on the open bug and try this again when the bug is solved (or fix it ourselves, any volunteers? 😊 )
