### ISSUE TITLE
undefined local variable or method `available_currencies' for #<Community:>

### ISSUE THREAD

**Issue by prakash-subramani** [sharetribe/sharetribe#2825]
##### Environment: Mac OS X

```
> node -v 
6.9.0
> npm -v 
3.10.9
```
##### Description:

The issue happens while updating "Add slogan & Description". It throws following error

`NameError - undefined local variable or method `available_currencies' for #<Community:0x007f8ad871fb00>:
13:42:01 rails.1               |   activemodel (4.2.7.1) lib/active_model/attribute_methods.rb:433:in `method_missing'
13:42:01 rails.1               |   app/models/community.rb:571:in `default_currency'
13:42:01 rails.1               |   /Users/prakash/.rvm/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/money-rails-1.4.1/lib/money-rails/active_record/monetizable.rb:202:in `block (2 levels) in monetize'
13:42:01 rails.1               |   /Users/prakash/.rvm/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/money-rails-1.4.1/lib/money-rails/active_record/monetizable.rb:114:in `block (2 levels) in monetize'
13:42:01 rails.1               |   activemodel (4.2.7.1) lib/active_model/validator.rb:149:in `block in validate'
13:42:01 rails.1               |   activemodel (4.2.7.1) lib/active_model/validator.rb:148:in `validate'
13:42:01 rails.1               |   activesupport (4.2.7.1) lib/active_support/callbacks.rb:455:in `block in make_lambda'
13:42:01 rails.1               |   activesupport (4.2.7.1) lib/active_support/callbacks.rb:192:in `block in simple'
13:42:01 rails.1               |   activesupport (4.2.7.1) lib/active_support/callbacks.rb:504:in `block in call'
13:42:01 rails.1               |   activesupport (4.2.7.1) lib/active_support/callbacks.rb:504:in `call'
13:42:01 rails.1               |   activesupport (4.2.7.1) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
13:42:01 rails.1               |   activesupport (4.2.7.1) lib/active_support/callbacks.rb:778:in `_run_validate_callbacks'
13:42:01 rails.1               |   activemodel (4.2.7.1) lib/active_model/validations.rb:399:in `run_validations!'
13:42:01 rails.1               |   activemodel (4.2.7.1) lib/active_model/validations/callbacks.rb:113:in `block in run_validations!'
`
##### Steps To Reproduce:

1.  Cloned & Configured all setups which mentioned in documentation 
2. Created new community and & logged in 
3. Click "Add slogan & Description" in top bar for progress complete, then add details and submit, then it will trows the error

Expected result: It would be redirect to next step
Actual result:  Method missing error

Any Help?

**Comment by rap1ds** [comment]
Hi! Thanks for reporting.

I can't reproduce this. I cloned 6cc7677, made a fresh install with fresh database, created new community, logged in, clicked add slogan in the top bar and then added the details and saved. The result was successful and I saw the wizard congratulations popup (The one with "Whoohou" text).

Could you add more details how to reproduce the issue? What country you used to create the marketplace?

The line that causes the issue is this: https://github.com/sharetribe/sharetribe/blob/6cc767763d657e36bc98128832d066770f958b9c/app/models/community.rb#L574 . In that line, `MoneyRails.default_currency` is called and for some reason `MoneyRails` is undefined. Have you run `bundle install` successfully? For some reason `MoneyRails` seems to be missing.

Btw. this piece of code has been removed from the most recent version of Sharetribe, so it might be that this is not issue anymore in the newest version (master branch HEAD).

**Comment by rap1ds** [comment]
Closing, inactive.
