### ISSUE TITLE
README order numbers are not right

### ISSUE THREAD

**Issue by xuanus** [sharetribe/sharetribe#2925]
**All order numbers are 1**
https://github.com/sharetribe/sharetribe/blob/master/README.md
----------------------------------------

<img width="589" alt="screen shot 2017-04-05 at 10 30 56 pm" src="https://cloud.githubusercontent.com/assets/9119888/24739198/af262d00-1a4f-11e7-897f-c0c02d045385.png">

**Comment by rap1ds** [comment]
Thanks for reporting!

Well, that's interesting! In Markdown the number in the list doesn't actually have any effect on the numbering. Writing list:

```
1. One
1. Two
1. Three
```

...should render:

```
1. One
2. Two
3. Three
```

The numbering in the README has been like this for ages, and it has worked well. Because they are not working anymore, I expect this to be recent change (or bug?) in the way how Github renders markdown.

**Comment by rap1ds** [comment]
**TODO:** Find out if the root cause for this issue is: a) Github markdown rendering b) Our syntax . If a), file a bug report or wait that they fix it. If b) fix the syntax.

**Comment by xuanus** [comment]
I am using rubymine plugin, the rendering result is 1. 1. 1. too
<img width="886" alt="screen shot 2017-04-05 at 11 54 44 pm" src="https://cloud.githubusercontent.com/assets/9119888/24741561/50ab1a86-1a5b-11e7-80f1-555a07d78de8.png">

**Comment by rap1ds** [comment]
Thanks for the additional information!

**Comment by acloudiator** [comment]
Adding an intendation should fix it.
sharetribe/README.md
