### ISSUE TITLE
Uncaught Error: Cannot find module "!!./../../css-loader/index.js

### ISSUE THREAD

**Issue by sunil-netsol** [sharetribe/sharetribe#3013]
i am setting up the sharetribe on mac. After logged into sharetribe redirected to http://localhost:5000/en/listings/new. On this screen form is not getting load. Console showing me the following error.

Uncaught Error: Cannot find module "!!./../../css-loader/index.js!./../../sass-loader/index.js!./styles.scss"
    at webpackMissingModule (eval at <anonymous> (application-9b06cd6….js:4299), <anonymous>:4:79)
    at eval (eval at <anonymous> (application-9b06cd6….js:4299), <anonymous>:4:228)
    at Object.<anonymous> (application-9b06cd6….js:4299)
    at __webpack_require__ (application-9b06cd6….js:73)
    at eval (eval at <anonymous> (application-9b06cd6….js:4293), <anonymous>:19:1)
    at Object.<anonymous> (application-9b06cd6….js:4293)
    at __webpack_require__ (application-9b06cd6….js:73)
    at eval (eval at <anonymous> (application-9b06cd6….js:4233), <anonymous>:37:35)
    at Object.<anonymous> (application-9b06cd6….js:4233)
    at __webpack_require__ (application-9b06cd6….js:73)
what is the wrong here.I could not find the solution for this error. 
Thanks in Advance.

**Comment by bladealslayer** [comment]
Which version of Sharetribe are you running? What version of `node` are you using? What output do you see when you run `foreman start -f Procfile.static`?

Please, use the issue reporting template in the future.

**Comment by mickeyren** [comment]
i'm also getting this error on `63cf226`running node v6.9.5.

**Comment by bladealslayer** [comment]
Closing as it seems inactive.

**Comment by rahmatullah5** [comment]
i got the errors as @sunil-netsol  , and i cant update the marketplace basic details 
![image](https://user-images.githubusercontent.com/16495060/28679036-2eba8262-731c-11e7-9510-92c2b6bb3958.png)

**Comment by aman29april** [comment]
I am also getting same error

**Comment by aman29april** [comment]
@bladealslayer 
Node version is 7.8.0
Output of foreman is 

20:12:50 rails-server-assets.1 | node: v7.8.0
20:12:50 rails-client-assets.1 | node: v7.8.0
20:12:50 rails-server-assets.1 | npm: v4.2.0
20:12:50 rails-client-assets.1 | npm: v4.2.0
20:12:52 rails-client-assets.1 | Webpack dev build for Rails
20:13:12 rails-server-assets.1 | Hash: b86de88de11af7cd06c2
20:13:12 rails-server-assets.1 | Version: webpack 1.13.3
20:13:12 rails-server-assets.1 | Time: 20714ms
20:13:12 rails-server-assets.1 |            Asset     Size  Chunks             Chunk Names
20:13:12 rails-server-assets.1 | server-bundle.js  3.84 MB       0  [emitted]  main
20:13:12 rails-server-assets.1 |    [0] multi main 40 bytes {0} [built]
20:13:12 rails-server-assets.1 |  [616] ./app/i18n/all.js 380 kB {0} [optional] [built]
20:13:12 rails-server-assets.1 |  [619] ./app/routes/routes.js 145 kB {0} [optional] [built]
20:13:12 rails-server-assets.1 |     + 975 hidden modules
20:13:16 rails-client-assets.1 | Hash: ad6a37865115c740b829
20:13:16 rails-client-assets.1 | Version: webpack 1.13.3
20:13:16 rails-client-assets.1 | Time: 23746ms
20:13:16 rails-client-assets.1 |            Asset     Size  Chunks             Chunk Names
20:13:16 rails-client-assets.1 |    app-bundle.js  8.74 MB       0  [emitted]  app
20:13:16 rails-client-assets.1 | vendor-bundle.js   408 kB       1  [emitted]  vendor
20:13:16 rails-client-assets.1 |   app-bundle.css  74.9 kB       0  [emitted]  app
20:13:16 rails-client-assets.1 |    [0] multi app 28 bytes {0} [built]
20:13:16 rails-client-assets.1 |    [0] multi vendor 40 bytes {1} [built]
20:13:16 rails-client-assets.1 |  [295] ./app/routes/routes.js 145 kB {0} [optional] [built]
20:13:16 rails-client-assets.1 |     + 704 hidden modules
20:13:16 rails-client-assets.1 | 
20:13:16 rails-client-assets.1 | ERROR in Missing binding /home/ubuntu/sharetribe/client/node_modules/node-sass/vendor/linux-x64-51/binding.node
20:13:16 rails-client-assets.1 | Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 7.x
20:13:16 rails-client-assets.1 | 
20:13:16 rails-client-assets.1 | Found bindings for the following environments:
20:13:16 rails-client-assets.1 |   - Linux 64-bit with Unsupported runtime (57)
20:13:16 rails-client-assets.1 | 
20:13:16 rails-client-assets.1 | This usually happens because your environment has changed since running `npm install`.
20:13:16 rails-client-assets.1 | Run `npm rebuild node-sass` to build the binding for your current environment.
20:13:16 rails-client-assets.1 |  @ ./~/react-dates/css/styles.scss 4:14-97
20:13:16 rails-client-assets.1 | Child extract-text-webpack-plugin

**Comment by mickeyren** [comment]
@bladealslayer try node version between v >6.9 <6.10. Staying between these version worked for me.

**Comment by aman29april** [comment]
@mickeyren If I downgrade node, then it gives error on running foreman
Wanted node version "7.8" (>=7.8.0 <7.9.0)

**Comment by mickeyren** [comment]
@aman29april and you are in `git checkout latest` ?

**Comment by aman29april** [comment]
@mickeyren Earlier I was on the master. Now I am on latest. Using node 6.9.5
But still same issue.

**Comment by mickeyren** [comment]
@aman29april did you `rm -rf node_modules` / `rm -rf client/node_modules` ? and run `npm install` again. 

that error should really start to go away - this is all what it took me to get it to run properly.

**Comment by aman29april** [comment]
@mickeyren Yes, I just removed node modules and did npm install again. It worked. 
Thanks.

**Comment by bipashant** [comment]
@mickeyren Fantastic, It worked! Thank you!!

**Comment by wesleyguirra** [comment]
Hello, I did: `git checkout latest` `nvm use 6.9.5` `rm -rf client/node_modules` `npm install` 

foreman outputs

```
14:27:35 rails-client-assets.1 | node: v6.9.5
14:27:35 rails-client-assets.1 | npm: v3.10.10
14:27:35 rails-client-assets.1 | Error: Wanted node version "7.8" (>=7.8.0 <7.9.0)
14:27:35 rails-client-assets.1 | Error: Wanted npm version "4.2.0" (4.2.0)
14:27:35 rails-client-assets.1 | To install node, run `nvm install 7.8` or check https://nodejs.org/
14:27:35 rails-client-assets.1 | To install npm, run `npm install -g npm@4.2.0`
```

**Comment by tannerhallman** [comment]
Any resolution ever found for this? I am getting same error as @wesleyguirra
