### ISSUE TITLE
Server crashes every time I close the ssh console 

### ISSUE THREAD

**Issue by alexlizogub** [sharetribe/sharetribe#3086]
Sharetribe Version: 7.1 (current)
Environment: 8099a97 Ubuntu 16.04

> node -v 7.8.0
> npm -v 4.2.0
Server mode: production

Description:
I run this in console and server starts
` bundle exec rails server -e production`
As soon as I close the terminal, I can't reach the website. 

What's the problem? 
How to remove :3000 port?

**Comment by pcm211** [comment]
Well ,

The process which you run is a user process and stops as soon as you close
the window

For keeping it running transfer the same to background root as server
process

There is a detailed write-up of mine for production environment settings

PORT 3000
to run services on well known ports again the permissions have to be
escalated accordingly and allowed in the server . Moreover please go
through one of my write-up on production environment settings which would
come in handy for all your questions and more importantly other problems
which you would encounter in future





On Sep 30, 2017 6:07 AM, "alexlizogub" <notifications@github.com> wrote:

Sharetribe Version: 7.1 (current)
Environment: 8099a97
<https://github.com/sharetribe/sharetribe/commit/8099a972d0eef3ad306405f23db65b75f32f874a>
Ubuntu 16.04

node -v 7.8.0
npm -v 4.2.0
Server mode: production

Description:
I run this in console and server starts
bundle exec rails server -e production
As soon as I close the terminal, I can't reach the website.

What's the problem?
How to remove :3000 port?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/sharetribe/sharetribe/issues/3086>, or mute the thread

**Comment by alexlizogub** [comment]
Hello, thank you for contribution

Where can I find your write-ups? 

Thanks!

**Comment by thomasmalbaux** [comment]
Thanks for reporting your experience! Indeed as it was mentioned if you close your terminal everything will be shutdown so you should use some kind of process manager. I'll close this now.

This has been discussed in Sharetribe's open-source Community forum at https://www.sharetribe.com/community/t/how-to-run-sharetribe-in-background/281/2
Don't hesitate to post more details there if you need help with your setup!
