### ISSUE TITLE
Location Search (Discovery Service) open source -- when?

### ISSUE THREAD

**Issue by xuanus** [sharetribe/sharetribe#3110]
Current Sharetribe open source version has no way to use Docker or Docker Compose to deploy in AWS, due to Sphinx is used for searching. 

May we know when the new search service used in sharetribe.com, Discovery Service, will be available in open source?

The community thread has not been updated for a long time.
https://www.sharetribe.com/community/t/location-search/348/2

Thank you very much.

**Comment by thomasmalbaux** [comment]
Hey Xuanus!

Thanks for sharing your experience. Indeed open-sourcing this feature hasn't moved forward and it isn't something we are working on right now.

We hope to release it in the future but I don't have any timeline to share. We'll update the Community forum post if we move forward with it so that's the best place where to get information about the open-source version updates.

Thanks!
