### ISSUE TITLE
New User registration - Newsletter settings are wrong

### ISSUE THREAD

**Issue by mecjack** [sharetribe/sharetribe#3380]
##### Description:

On user sign up (registration), if new user does not check the person_admin_emails_consent, then the user will however see in his settings/notifications page a checked weekly newsletter radio button!  This must  be set to 'don't send me newsletters' because of privacy policy.

##### Additional information

To fix this, one could add the following code to the new_person function in the people_controller right before 'person.save':

if (admin_emails_consent != "on")
  person.min_days_between_community_updates = 100000
end

**Comment by thomasmalbaux** [comment]
Hi there,

thanks for reporting!

Indeed, the current behavior is by design.

In this context, "Newsletters" means the automatic daily or weekly email that contains up to 10 of the latest listings recently added to the marketplace. This is an automatic newsletter and admins can't edit their content, or add personal messages there.

We believe that such automatic notification is part of the regular service of the marketplace, and doesn't requires extra approval.
Members can also unsubscribe from such automatic newsletter anytime (from their settings or the email footer).

However, messages send from admins (often unique), are different and, indeed, requires approval from members.

Does it clarify things?
