### ISSUE TITLE
Per hour availability calendar 

### ISSUE THREAD

**Issue by Chuseuiti** [sharetribe/sharetribe#4192]
Couldnt find the per hour availability calendar feature under the Edit Listing or Listing field and filters, how is it possible to activate it?
Link to Sharetribe documentation:
https://help.sharetribe.com/en/articles/1427860-manage-booking-availability-per-hour

![image](https://user-images.githubusercontent.com/6238840/93030973-284aba00-f5f5-11ea-8ad1-b063e056bc75.png)

**Comment by thomasmalbaux** [comment]
Hi there!

You can enable the "Per hour" pricing unit with availability by adding/editing your _Order types_.

![order-types_per-hour](https://user-images.githubusercontent.com/2463785/93057110-12c9a480-f676-11ea-8d3c-31214ceffa08.png)

Hopefully this helps.

**Comment by vincentctor** [comment]
> Hi there!
> 
> You can enable the "Per hour" pricing unit with availability by adding/editing your _Order types_.
> 
> ![order-types_per-hour](https://user-images.githubusercontent.com/2463785/93057110-12c9a480-f676-11ea-8d3c-31214ceffa08.png)
> 
> Hopefully this helps.

Could we allow sellers to manage their availability on a calendar, but keeping the "Per person" pricing unit?

We provide experiences (instead of booking of facilities) and we charge per person per session. 

I think this is a very critical feature for marketplaces for services/experiences that are task-based rather than hourly-based.

**Comment by thomasmalbaux** [comment]
Discussion continues at https://github.com/sharetribe/sharetribe/issues/4352
