### ISSUE TITLE
Setting up Braintree Payment Gateway(sandbox) in Production Environment

### ISSUE THREAD

**Issue by usmanarif** [sharetribe/sharetribe#905]
I am setting up the Braintree Payment Gateway in my app in production environment. After doing the same and on purchasing listing I am redirected to

    http://b2*************.com/en/listings/10/preauthorized?person_id=aX9*****************hDg

with the message

    Page loading failed! Reloading/redirecting...........in the box below.

Though I have provided the Braintree Credentials i.e keys from Admin and also purchasing the listings using dummy account and routing number. I have setup the webhooks and getting a long number after clicking on webhook url provided.
I have also checked the log but didn't getting any error message. Please tell what I am missing and where can I find the steps required to follow for setting up Braintree Payment Gateway in my application.

**Comment by bingxie** [comment]
+1
we need a specific document for setting up the Braintree Payment Gateway.

**Comment by sktoiva** [comment]
At the moment, we have other pressing issues on our  backlog so writing documentation to Braintree isn't high on the list. That being said, one thing to check is that have you configured the Webhook URI to Braintree? 
After you have configured the payment gateway through admin UI, you need to navigate to Braintree Payments, log in and create a new webhook and provide the generated URI there. We don't have any means to automatically send the webhook to Braintree so that needs to be done manually.

Hope this helps!
