### ISSUE TITLE
s3 url suffix

### ISSUE THREAD

**Issue by younes0** [sharetribe/sharetribe#943]
s3 upload works fine but I get this suffix in links:
`https://mybucket.s3.amazonaws.com/images/listing_images/images/7/big/garden.jpg%3F1422089097`

**Comment by rap1ds** [comment]
Can you explain what is the issue here?

**Comment by younes0** [comment]
If you look at the url, `%3F1422089097` is added at the end of the link which brokes it.
All uploaded assets to S3 are served with a similar suffix.

**Comment by rap1ds** [comment]
Right, indeed that is a bit broken.

Instead of `%3F` there should be question mark `?`, i.e. https://mybucket.s3.amazonaws.com/images/listing_images/images/7/big/garden.jpg?1422089097

Where do you see this link? In listing page? Do you have any additional info how could I reproduce the issue. In my local environment and in sharetribe.com production environment, the question mark is there as it should.

**Comment by younes0** [comment]
It happens in all pages: it concerns all S3 assets links.
That didn't happen in my local environnment which is the same env for my staging where error is produced (ubuntu, utf8 databases, same ruby installation).

**Comment by rap1ds** [comment]
Well that is weird. I haven't seen this before and I have no idea what might be the cause...

**Comment by younes0** [comment]
Could you please tell me where in the code that sufix is added ? guess it's for caching purposes

**Comment by rap1ds** [comment]
It is for caching purpuses. It's automatically added by Rails.

**Comment by younes0** [comment]
Thanks. Solved: http://stackoverflow.com/questions/27112699/rails-4-paperclip-s3-wrong-url-path

**Comment by rap1ds** [comment]
Great that you found the reason! Thanks for the SO link!
