### ISSUE TITLE
docker issue: Error starting userland proxy ...

### ISSUE THREAD

**Issue by Kanann** [sharetribe/sharetribe#944]
Hi, I am following the guideline to launch sharetribe with docker.
I have installed mysql, docker and fig, but I have an issue when putting this command : 
<i>sudo fig run web /bin/bash -l -c 'bundle exec rake db:schema:load'</i>

Here is the response : 
<i>Starting dockersharetribe_dbtest_1...
Starting dockersharetribe_db_1...
Cannot start container c591c5b2c938e2fb37b2061db7376abd3c8c5f6a79410e5fb2eb23d4fd5e19e4: Error starting userland proxy: listen tcp 0.0.0.0:3306: bind: address already in use</i>

It seems there is a conflict with mysql db using the port 3306. 
If I stop mysql, there is no more error with "sudo fig run web", but 127.0.1.1:3000 (or docker.lvh.me:3000) returns nothing since (I guess) the mysql database is stopped. After this, mysql cannot be restarted, because of a new conflict.

I don't understand why sharetribe docker can't run at the same time of the mysql server while it needs it for working.
Do you have a solution for this problem ?

**Comment by rap1ds** [comment]
Hi!

Nice to hear you are trying out the Docker installation! It's still very experimental and we are not using it yet on production, only testing it on local dev environments.

Indeed, there seems to be a conflict. The problem is you local MySQL server, which conflicts with the MySQL container. If you use Fig and Docker, you don't need a local MySQL server. Instead, you should actually stop your server. Fig will download MySQL Docker image and run a MySQL container.

Maybe you could try a fresh installation? Stop your local MySQL server, and remove all the docker images and containers and try the installation steps again.

**Comment by Kanann** [comment]
Thank you. Ok I didn't get that Fig was downloading a MySQL Docker image and running a MySQL container, so that I don't need a local MySQL server.
You're right, I will try a fresh installation and tell you if it's ok.
Thanks !

**Comment by rap1ds** [comment]
You welcome! Let me know if you experience other issues. We are still trying how Docker would fit to our stack so it's nice to hear some user feedback!
