### ISSUE TITLE
generate_customization_stylesheets task 

### ISSUE THREAD

**Issue by farukaydin** [sharetribe/sharetribe#976]
I have a problem with ```sharetribe:generate_customization_stylesheets``` task. Althought it generates precompiled custom stylesheet like ```public/assets/custom-style-xxxx-20150209035047.css```  in production environment(I use heroku as deployment platform) I can't reach by typing website_path/assets/customcustom-style-xxxx-20150209035047.css Is there any additional configuration to use it properly?

**Comment by rap1ds** [comment]
We use a little bit different setup with sharetribe.com. Instead of saving the stylesheet to Heroku, we use Amazon S3 to host the static file. I strongly recommend that to use, since it's waste of Heroku dyno capacity to serve static assets directly from the dyno.

In order to do that, you should setup a S3 bucket and then will in the configurations in your config.yml
